comptable_index:
    path:     /
    defaults: { _controller: "GestionFraisBundle:Comptable:RerchercherFicheFrais" }

comptable_rechercherfichefrais:
    path:      /fichefrais/rechercher
    defaults: { _controller: "GestionFraisBundle:Comptable:RerchercherFicheFrais" }

comptable_vaiderfichefrais:
    path:    /fichefrais/valider/{idFicheFrais}
    defaults: { _controller: "GestionFraisBundle:Comptable:validerFicheFrais" }

comptable_consulterfichefrais:
    path:    /fichefrais/consulter/{idFicheFrais}
    defaults: { _controller: "GestionFraisBundle:Comptable:ConsulterFicheFrais" }

comptable_fichesfraiscloturer:
    path:    /fichefrais/cloturer
    defaults: { _controller: "GestionFraisBundle:Comptable:cloturerFicheFrais" }

comptable_lignefraisforfait:
    path:    /lignefraisforfait/{operation}/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:ligneFraisForfait" }

comptable_lignefraishorsforfait:
    path:    /lignefraishorsforfait/{operation}/{idLigneFraisHorsForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:ligneFraisHorsForfait" }

