utilisateur_index:
      path:     /
      defaults: { _controller: "GestionFraisBundle:Utilisateur:saisirFrais" }

utilisateur_saisirFrais:
    path:     /saisirfrais
    defaults: { _controller: "GestionFraisBundle:Utilisateur:saisirFrais" }

utilisateur_rechercherfichefrais:
    path:     /rechercherfiche
    defaults: { _controller: "GestionFraisBundle:Utilisateur:RercherFicheFrais" }

utilisateur_consulterfichefrais:
    path:    /fichefrais/consulter/{idFicheFrais}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ConsulterFicheFrais" }

utilisateur_lignefraisforfait:
    path:    /lignefraisforfait/{operation}/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ligneFraisForfait" }

utilisateur_lignefraishorsforfait:
    path:    /lignefraishorsforfait/{operation}/{idLigneFraisHorsForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ligneFraisHorsForfait" }





