utilisateur_index:
      path:     /
      defaults: { _controller: "GestionFraisBundle:Utilisateur:Index" }

utilisateur_fichefrais:
     resource: "@GestionFraisBundle/Resources/config/routing/utilisateur/fichefrais.yml"
     prefix:   /fichefrais

gestion_frais_lignefraishorsforfait:
    resource: "@GestionFraisBundle/Resources/config/routing/utilisateur/lignefraishorsforfait.yml"
    prefix:   /lignefraishorsforfait