utilisateur_index:
    path:   /
    defaults: { _controller: "GestionFraisBundle:Utilisateur:Index" }

utilisateur_consulter:
    path:     /consulter/{mois}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ConsulterFiche" }

utilisateur_renseigner:
    path:     /renseigner/{mois}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:RenseignerFiche" }

utilisateur_enregistrer:
    path:     /enregistrer/{mois}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:EnregistrerFiche" }
