utilisateur_consulter:
    path:     /consulter/{mois}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ConsulterFiche" }

utilisateur_renseigner:
    path:     /renseigner/{mois}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:RenseignerFiche" }