fichefrais_index:
    path:     /
    defaults: { _controller: "GestionFraisBundle:Comptable:Index" }

ficheFrais_valider:
    path:     /valider/{idFicheFrais}
    defaults: { _controller: "GestionFraisBundle:Comptable:ValiderFiche" }

