fichefrais_index:
    path:     /
    defaults: { _controller: "GestionFraisBundle:Comptable:index" }

fichefrais_valider:
    path:     /{id}/valider
    defaults: { _controller: "GestionFraisBundle:Comptable:valider" }

fichefrais_modifier:
    path:     /new
    defaults: { _controller: "GestionFraisBundle:Comptable:modifier" }

fichefrais_create:
    path:     /create
    defaults: { _controller: "GestionFraisBundle:FicheFrais:create" }
    methods:  POST

fichefrais_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestionFraisBundle:FicheFrais:edit" }

fichefrais_update:
    path:     /{id}/update
    defaults: { _controller: "GestionFraisBundle:FicheFrais:update" }
    methods:  [POST, PUT]

fichefrais_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestionFraisBundle:FicheFrais:delete" }
    methods:  [POST, DELETE]
