lignefraishorsforfait:
    path:     /
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:index" }

lignefraishorsforfait_show:
    path:    /show/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:show" }

lignefraishorsforfait_new:
    path:     /new
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:new" }

lignefraishorsforfait_create:
    path:     /create
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:create" }
    methods:  POST

lignefraishorsforfait_edit:
    path:     /edit/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:edit" }

lignefraishorsforfait_update:
    path:     /update/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:update" }
    methods:  [POST, PUT]

lignefraishorsforfait_delete:
    path:     /delete/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:delete" }
    methods:  [POST, DELETE]

    defaults: { _controller: "GestionFraisBundle:Comptable:consulterLigneFraisForfait" }

comptable_validerlignefraishorsforfait:
    path:    /lignefraishorsforfait/valider/{idLigneFraisHorsForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:validerLigneFraisHorsForfait" }

comptable_consulterlignefraishorsforfait:
    path:    /lignefraishorsforfait/consulter/{idLigneFraisHorsForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:consulterLigneFraisHorsForfait" }
