lignefraisforfait_valider:
    path:    /valider/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:validerLigneFraisForfait" }

utilisateur_suprimerlignefraisforfait:
    path:    /lignefraisforfait/suprimer/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:suprimerLigneFraisForfait" }

comptable_validerlignefraisforfait:
    path:    /lignefraisforfait/valider/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:validerLigneFraisForfait" }

comptable_consulterlignefraisforfait:
    path:    /lignefraisforfait/consulter/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Comptable:consulterLigneFraisForfait" }
