gestion_frais:
    resource: "@GestionFraisBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


gestion_frais_utilisateur:
    resource: "@GestionFraisBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur

gestion_frais_comptable:
    resource: "@GestionFraisBundle/Resources/config/routing/comptable.yml"
    prefix:   /comptable