gestion_frais:
    resource: "@GestionFraisBundle/Resources/config/routing/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


gestion_frais_utilisateur:
    resource: "@GestionFraisBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur

gestion_frais_comptable:
    resource: "@GestionFraisBundle/Resources/config/routing/comptable.yml"
    prefix:   /comptable

gestion_frais_administrateur:
    resource: "@GestionFraisBundle/Resources/config/routing/administrateur.yml"
    prefix:   /administrateur

gestion_frais_test:
    path:     /test
    defaults: { _controller: "GestionFraisBundle:Test:test" }

visiteur_modifiermotdepasse:
    path:    /modifiermotdepasse
    defaults: { _controller: "GestionFraisBundle:Default:MofidierMotDePasse"}

visiteur_modifiercoordonnee:
    path:    /modifiercoordonnee
    defaults: { _controller: "GestionFraisBundle:Default:MofidierCoordonnee"}

