ficheFrais_rechercher:
    path:     /rechercher
    defaults: { _controller: "GestionFraisBundle:Utilisateur:RercherFicheFrais" }

ficheFrais_afficher:
    path:    /afficher/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:afficherFicheFrais" }

ficheFrais_consulter:
    path:    /consulter/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ConsulterFicheFrais" }
