ficheFrais_index:
    path:     /
    defaults: { _controller: "GestionFraisBundle:Utilisateur:Index" }

ficheFrais_ajouter:
    path:     /ajouter
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterFicheFrais" }

ficheFrais_afficher:
    path:    /afficher/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:afficherFicheFrais" }

ficheFrais_consulter:
    path:    /consulter/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ConsulterFicheFrais" }

ficheFrais_renseigner:
    path:    /renseigner/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:Renseigner" }

ficheFrais_enregistrer:
    path:     /enregistrer/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:Enregistrer" }
