lignefraisforfait_afficher:
    path:    /afficher/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:afficherlignefraisForfait" }

lignefraisforfait_ajouter:
    path:     /ajouter
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterlignefraisForfait" }

lignefraisforfait_modifier:
    path:     /modifier/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:modifierlignefraisForfait" }

lignefraisforfait_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:supprimerlignefraisForfait" }


utilisateur_ajouterlignefraisforfait:
    path:    /lignefraisforfait/ajouter/
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterLigneFraisForfait" }

utilisateur_modifierlignefraisforfait:
    path:    /lignefraisforfait/modifier/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:modifierLigneFraisForfait" }

utilisateur_consulterlignefraisforfait:
    path:    /lignefraisforfait/consulter/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:consulterLigneFraisForfait" }

utilisateur_suprimerlignefraisforfait:
    path:    /lignefraisforfait/suprimer/{idLigneFraisForfait}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:suprimerLigneFraisForfait" }