lignefraishorsforfait_afficher:
    path:    /afficher/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:afficherLigneFraisHorsForfait" }

lignefraishorsforfait_ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterLigneFraisHorsForfait" }

lignefraishorsforfait_modifier:
    path:     /modifier/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:modifierLigneFraisHorsForfait" }

lignefraishorsforfait_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:supprimerLigneFraisHorsForfait" }
