lignefraisforfait_afficher:
    path:    /afficher/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:afficherlignefraisForfait" }

lignefraisforfait_ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterlignefraisForfait" }

lignefraisforfait_modifier:
    path:     /modifier/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:modifierlignefraisForfait" }

lignefraisforfait_supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:supprimerlignefraisForfait" }
