lignefraishorsforfait:
    path:     /
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:index" }

lignefraishorsforfait_show:
    path:    /show/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:show" }

lignefraishorsforfait_new:
    path:     /new/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:ajouterLigneFraisHorsForfait" }

lignefraishorsforfait_create:
    path:     /create
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:create" }
    methods:  POST

lignefraishorsforfait_edit:
    path:     /edit/{id}
    defaults: { _controller: "GestionFraisBundle:Utilisateur:modifierLigneFraisHorsForfait" }

lignefraishorsforfait_update:
    path:     /update/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:update" }
    methods:  [POST, PUT]

lignefraishorsforfait_delete:
    path:     /delete/{id}
    defaults: { _controller: "GestionFraisBundle:LigneFraisHorsForfait:delete" }
    methods:  [POST, DELETE]
