<?php

namespace Proxies\__CG__\GestionFraisBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FicheFrais extends \GestionFraisBundle\Entity\FicheFrais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'idVisiteur', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'mois', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'idEtatFicheFrais', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'dateModif');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'idVisiteur', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'mois', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'idEtatFicheFrais', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'montantValide', '' . "\0" . 'GestionFraisBundle\\Entity\\FicheFrais' . "\0" . 'dateModif');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FicheFrais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdVisiteur($idVisiteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVisiteur', array($idVisiteur));

        return parent::setIdVisiteur($idVisiteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVisiteur()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdVisiteur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVisiteur', array());

        return parent::getIdVisiteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMois($mois)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMois', array($mois));

        return parent::setMois($mois);
    }

    /**
     * {@inheritDoc}
     */
    public function getMois()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getMois();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMois', array());

        return parent::getMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEtatFicheFrais($idEtatFicheFrais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEtatFicheFrais', array($idEtatFicheFrais));

        return parent::setIdEtatFicheFrais($idEtatFicheFrais);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEtatFicheFrais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEtatFicheFrais', array());

        return parent::getIdEtatFicheFrais();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantValide($montantValide)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantValide', array($montantValide));

        return parent::setMontantValide($montantValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantValide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantValide', array());

        return parent::getMontantValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', array($dateModif));

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', array());

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJustificatif($nbJustificatif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJustificatif', array($nbJustificatif));

        return parent::setNbJustificatif($nbJustificatif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJustificatif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJustificatif', array());

        return parent::getNbJustificatif();
    }

}
