#GestionFraisBundle/Resources/config/routing_rest.yml

gestion_frais :
  type: rest
  resource:     "GestionFraisBundle:WebServiceRest"
  name_prefix:  api_

api_connection:
    path:    /connexion/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:WebServiceRest:getConnexion" }
    requirements:
          _format:  json
          requette:     .+

api_fichefrais:
    path:    /fichefrais/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:WebServiceRest:getficheFrais" }
    requirements:
          _format:  json
          requette:     .+


api_lesfichefrais:
    path:    /lesfichesfrais/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:WebServiceRest:getlesFicheFrais" }
    requirements:
          _format:  json
          requette:     .+

