#GestionFraisBundle/Resources/config/routing_rest.yml

gestion_frais :
  type: rest
  resource:     "GestionFraisBundle:WebServiceRest"
  name_prefix:  api_

api_connection:
    path:    /connection/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:WebServiceRest:getConnetion" }
    requirements:
          _format:  json
          requette:     .+


api_lesfichefrais:
    path:    /lesfichefrais/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:WebServiceRest:getlesFicheFrais" }
    requirements:
          _format:  json
          requette:     .+

