gestion_frais_fichefrais:
    resource: "@GestionFraisBundle/Resources/config/routing/fichefrais.yml"
    prefix:   /fichefrais

gestion_frais_fraisforfait:
    resource: "@GestionFraisBundle/Resources/config/routing/fraisforfait.yml"
    prefix:   /fraisforfait

gestion_frais_etatlignefrais:
    resource: "@GestionFraisBundle/Resources/config/routing/etatlignefrais.yml"
    prefix:   /etatlignefrais

gestion_frais_etatfichefrais:
    resource: "@GestionFraisBundle/Resources/config/routing/etatfichefrais.yml"
    prefix:   /etatfichefrais

gestion_frais_visiteur:
    resource: "@GestionFraisBundle/Resources/config/routing/visiteur.yml"
    prefix:   /visiteur

gestion_frais_homepage:
    path:     /hello/
    defaults: { _controller: GestionFraisBundle:Default:index }
