Gestion_frais_homepage:
    path:     /
    defaults: { _controller: "GestionFraisBundle:Default:Index" }

gestion_frais_fichefrais:
    resource: "@GestionFraisBundle/Resources/config/routing/Comptable/FicheFrais.yml"
    prefix:   /FicheFrais

gestion_frais_test:
    path:     /test/{requette}.{_format}
    defaults: { _controller: "GestionFraisBundle:Default:test" }
    requirements:
              _format:  json
              requette:     .+

