services:
#    gestion_frais.example:
#        class: GestionFraisBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    gestion_frais.gestionairefiche:
        class: GestionFraisBundle\GestionFiche\GestionFicheController
        arguments: ["@service_container"]

